#!/usr/bin/env bash
# Local dual-arch package + publish GitHub Release (version from Cargo.toml).
#
# Preferred release path when GitHub Actions has no macOS minutes.
# Requires: macOS, rustup targets for both apple arches, gh auth, network.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

PACKAGE_SH="$ROOT/scripts/package-macos.sh"
DIST="${DIST:-$ROOT/dist}"

SKIP_BUILD=0
DRY_RUN=0
DRAFT=0
NOTES_FILE=""
TITLE=""
# When 1, do not create/push a git tag (gh release still uses tag name).
NO_GIT_TAG=0

usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

  Package aarch64 + x86_64 DMG/zip from the version in Cargo.toml, then create
  (or update) a GitHub Release with those assets via \`gh\`.

Options:
  --skip-build       Reuse existing dist artifacts (must match version)
  --dry-run          Build/package only; do not tag or publish
  --draft            Create the release as a draft
  --no-git-tag       Do not create/push a local git tag (gh still tags the release)
  --notes-file FILE  Release notes markdown (default: auto-generated by gh)
  --title TITLE      Release title (default: "Kimini v<version>")
  -h, --help         Show this help

Environment:
  DIST               Output directory (default: ./dist)
  GH_REPO            Override repo (default: gh remote resolution)

Examples:
  make publish-release
  ./scripts/publish-release.sh
  ./scripts/publish-release.sh --dry-run
  ./scripts/publish-release.sh --skip-build --draft
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --skip-build) SKIP_BUILD=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    --draft) DRAFT=1; shift ;;
    --no-git-tag) NO_GIT_TAG=1; shift ;;
    --notes-file)
      NOTES_FILE="${2:-}"
      if [[ -z "$NOTES_FILE" ]]; then
        echo "error: --notes-file requires a path" >&2
        exit 1
      fi
      shift 2
      ;;
    --title)
      TITLE="${2:-}"
      if [[ -z "$TITLE" ]]; then
        echo "error: --title requires a string" >&2
        exit 1
      fi
      shift 2
      ;;
    -h|--help) usage; exit 0 ;;
    *)
      echo "error: unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "error: local dual-arch packaging requires macOS" >&2
  exit 1
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "error: gh CLI not found (brew install gh && gh auth login)" >&2
  exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "error: gh is not authenticated (run: gh auth login)" >&2
  exit 1
fi

VERSION="$(
  awk -F'"' '/^version[[:space:]]*=/{print $2; exit}' Cargo.toml
)"
if [[ -z "$VERSION" ]]; then
  echo "error: could not read version from Cargo.toml" >&2
  exit 1
fi

TAG="v${VERSION}"
if [[ -z "$TITLE" ]]; then
  TITLE="Kimini ${TAG}"
fi

ARTIFACTS=(
  "${DIST}/Kimini-${VERSION}-macos-aarch64.dmg"
  "${DIST}/Kimini-${VERSION}-macos-aarch64.zip"
  "${DIST}/Kimini-Web-${VERSION}-macos-aarch64.dmg"
  "${DIST}/Kimini-Web-${VERSION}-macos-aarch64.zip"
  "${DIST}/Kimini-${VERSION}-macos-x86_64.dmg"
  "${DIST}/Kimini-${VERSION}-macos-x86_64.zip"
  "${DIST}/Kimini-Web-${VERSION}-macos-x86_64.dmg"
  "${DIST}/Kimini-Web-${VERSION}-macos-x86_64.zip"
)

echo "==> version ${VERSION}  tag ${TAG}"
echo "    title: ${TITLE}"
if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "    mode: dry-run (no tag / no publish)"
fi

if [[ -n "$(git status --porcelain 2>/dev/null || true)" ]]; then
  echo "warning: working tree is dirty — release will point at current HEAD" >&2
  git status --short >&2 || true
fi

# Prefer rustup-managed cargo so cross targets resolve.
if [[ -x "${CARGO_HOME:-$HOME/.cargo}/bin/cargo" ]]; then
  export PATH="${CARGO_HOME:-$HOME/.cargo}/bin:$PATH"
fi

if [[ "$SKIP_BUILD" -eq 0 ]]; then
  if command -v rustup >/dev/null 2>&1; then
    rustup target add aarch64-apple-darwin x86_64-apple-darwin
  fi
  echo "==> package both apps for aarch64 + x86_64 (DMG + zip)"
  for app in native web; do
    bash "$PACKAGE_SH" --app "$app" --target aarch64-apple-darwin --arch aarch64 --dmg --zip
    bash "$PACKAGE_SH" --app "$app" --target x86_64-apple-darwin --arch x86_64 --dmg --zip
  done
else
  echo "==> skip build; expecting existing artifacts in ${DIST}"
fi

missing=0
for f in "${ARTIFACTS[@]}"; do
  if [[ ! -f "$f" ]]; then
    echo "error: missing artifact: $f" >&2
    missing=1
  fi
done
if [[ "$missing" -ne 0 ]]; then
  echo "hint: run without --skip-build, or fix DIST/VERSION" >&2
  exit 1
fi

echo "==> artifacts"
ls -lh "${ARTIFACTS[@]}"
for f in "${ARTIFACTS[@]}"; do
  # zip is a container; dmg/app binary checks are best-effort via file(1)
  file -b "$f" | sed "s|^|    $(basename "$f"): |"
done

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo
  echo "Dry-run complete. Would publish:"
  echo "  tag:    $TAG"
  echo "  title:  $TITLE"
  printf '  assets:\n'
  for f in "${ARTIFACTS[@]}"; do
    echo "    - $f"
  done
  exit 0
fi

# Optional local git tag so the release points at a named ref in the clone.
if [[ "$NO_GIT_TAG" -eq 0 ]]; then
  if git rev-parse "$TAG" >/dev/null 2>&1; then
    existing="$(git rev-list -n 1 "$TAG")"
    head="$(git rev-parse HEAD)"
    if [[ "$existing" != "$head" ]]; then
      echo "error: tag $TAG already exists at $existing, but HEAD is $head" >&2
      echo "  bump Cargo.toml version, or delete the tag if it was a mistake" >&2
      exit 1
    fi
    echo "==> git tag $TAG already points at HEAD"
  else
    echo "==> git tag $TAG"
    git tag -a "$TAG" -m "Kimini ${TAG}"
  fi

  # Push tag if remote is missing it (best-effort detect origin).
  remote="$(git remote 2>/dev/null | awk 'NR==1{print; exit}')"
  remote="${remote:-origin}"
  if git ls-remote --tags "$remote" "refs/tags/${TAG}" 2>/dev/null | rg -q .; then
    echo "==> remote ${remote} already has ${TAG}"
  else
    echo "==> git push ${remote} ${TAG}"
    git push "$remote" "$TAG"
  fi
fi

# Publish or re-upload assets on an existing release.
release_args=(
  release create "$TAG"
  --title "$TITLE"
  --verify-tag
)
if [[ "$DRAFT" -eq 1 ]]; then
  release_args+=(--draft)
fi
if [[ -n "$NOTES_FILE" ]]; then
  release_args+=(--notes-file "$NOTES_FILE")
else
  release_args+=(--generate-notes)
fi
# Pre-release when version has a hyphen (e.g. 0.2.0-rc.1)
if [[ "$VERSION" == *-* ]]; then
  release_args+=(--prerelease)
fi

if gh release view "$TAG" >/dev/null 2>&1; then
  echo "==> release $TAG exists; uploading assets (clobber)"
  gh release upload "$TAG" "${ARTIFACTS[@]}" --clobber
  if [[ "$DRAFT" -eq 0 ]]; then
    # Ensure non-draft if caller wants a published release
    gh release edit "$TAG" --draft=false >/dev/null 2>&1 || true
  fi
else
  echo "==> gh ${release_args[*]} + assets"
  # --verify-tag fails if tag was not pushed (--no-git-tag); drop it then.
  if [[ "$NO_GIT_TAG" -eq 1 ]]; then
    filtered=()
    for a in "${release_args[@]}"; do
      [[ "$a" == "--verify-tag" ]] && continue
      filtered+=("$a")
    done
    release_args=("${filtered[@]}")
    release_args+=(--target "$(git rev-parse HEAD)")
  fi
  gh "${release_args[@]}" "${ARTIFACTS[@]}"
fi

echo
echo "Done. Release: $(gh release view "$TAG" --json url -q .url 2>/dev/null || echo "$TAG")"
echo "Assets:"
for f in "${ARTIFACTS[@]}"; do
  echo "  - $(basename "$f")"
done
