#!/usr/bin/env bash
# Local dual-arch package + publish GitHub Release (version from Cargo.toml).
#
# Preferred release path when GitHub Actions has no macOS minutes.
# Requires: macOS, rustup targets for both apple arches, gh auth, network.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

PACKAGE_SH="$ROOT/scripts/package-macos.sh"
DIST="${DIST:-$ROOT/dist}"
SPARKLE_ROOT="${SPARKLE_ROOT:-$ROOT/.sparkle}"
SPARKLE_ACCOUNT="${SPARKLE_ACCOUNT:-kimini.reedchan7}"
SIGN_SPARKLE_UPDATE="$ROOT/scripts/sign-sparkle-update.sh"

SKIP_BUILD=0
DRY_RUN=0
DRAFT=0
NOTES_FILE=""
TITLE=""
# When 1, do not create/push a git tag (gh release still uses tag name).
NO_GIT_TAG=0
INCLUDE_PORTABLE=0

usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

  Package aarch64 + x86_64 DMG/zip from the version in Cargo.toml, then create
  (or update) a GitHub Release with those assets via \`gh\`.

Options:
  --skip-build       Reuse existing dist artifacts (must match version)
  --dry-run          Build/package only; do not tag or publish
  --draft            Create the release as a draft
  --no-git-tag       Do not create/push a local git tag (gh still tags the release)
  --include-portable Require Linux/Windows x86_64 + ARM64 portable archives
  --notes-file FILE  Release notes markdown (default: auto-generated by gh)
  --title TITLE      Release title (default: "Kimini v<version>")
  -h, --help         Show this help

Environment:
  DIST               Output directory (default: ./dist)
  GH_REPO            Override repo (default: gh remote resolution)
  SPARKLE_ACCOUNT    Update signing keychain account (default: kimini.reedchan7)
  SPARKLE_PRIVATE_KEY_FILE
                     Optional exported Ed25519 private-key file for signing

Examples:
  make publish-release
  ./scripts/publish-release.sh
  ./scripts/publish-release.sh --dry-run
  ./scripts/publish-release.sh --skip-build --draft
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --skip-build) SKIP_BUILD=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    --draft) DRAFT=1; shift ;;
    --no-git-tag) NO_GIT_TAG=1; shift ;;
    --include-portable) INCLUDE_PORTABLE=1; shift ;;
    --notes-file)
      NOTES_FILE="${2:-}"
      if [[ -z "$NOTES_FILE" ]]; then
        echo "error: --notes-file requires a path" >&2
        exit 1
      fi
      shift 2
      ;;
    --title)
      TITLE="${2:-}"
      if [[ -z "$TITLE" ]]; then
        echo "error: --title requires a string" >&2
        exit 1
      fi
      shift 2
      ;;
    -h|--help) usage; exit 0 ;;
    *)
      echo "error: unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "error: local dual-arch packaging requires macOS" >&2
  exit 1
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "error: gh CLI not found (brew install gh && gh auth login)" >&2
  exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "error: gh is not authenticated (run: gh auth login)" >&2
  exit 1
fi

VERSION="$(
  awk -F'"' '/^version[[:space:]]*=/{print $2; exit}' Cargo.toml
)"
if [[ -z "$VERSION" ]]; then
  echo "error: could not read version from Cargo.toml" >&2
  exit 1
fi

TAG="v${VERSION}"
if [[ -z "$TITLE" ]]; then
  TITLE="Kimini ${TAG}"
fi

PACKAGES=(
  "${DIST}/Kimini-${VERSION}-macos-aarch64.dmg"
  "${DIST}/Kimini-${VERSION}-macos-aarch64.zip"
  "${DIST}/Kimini-Web-${VERSION}-macos-aarch64.dmg"
  "${DIST}/Kimini-Web-${VERSION}-macos-aarch64.zip"
  "${DIST}/Kimini-${VERSION}-macos-x86_64.dmg"
  "${DIST}/Kimini-${VERSION}-macos-x86_64.zip"
  "${DIST}/Kimini-Web-${VERSION}-macos-x86_64.dmg"
  "${DIST}/Kimini-Web-${VERSION}-macos-x86_64.zip"
)
PORTABLE_PACKAGES=(
  "${DIST}/Kimini-${VERSION}-linux-aarch64.tar.gz"
  "${DIST}/Kimini-${VERSION}-linux-aarch64.tar.gz.sha256"
  "${DIST}/Kimini-Web-${VERSION}-linux-aarch64.tar.gz"
  "${DIST}/Kimini-Web-${VERSION}-linux-aarch64.tar.gz.sha256"
  "${DIST}/Kimini-${VERSION}-linux-x86_64.tar.gz"
  "${DIST}/Kimini-${VERSION}-linux-x86_64.tar.gz.sha256"
  "${DIST}/Kimini-Web-${VERSION}-linux-x86_64.tar.gz"
  "${DIST}/Kimini-Web-${VERSION}-linux-x86_64.tar.gz.sha256"
  "${DIST}/Kimini-${VERSION}-windows-aarch64.zip"
  "${DIST}/Kimini-${VERSION}-windows-aarch64.zip.sha256"
  "${DIST}/Kimini-Web-${VERSION}-windows-aarch64.zip"
  "${DIST}/Kimini-Web-${VERSION}-windows-aarch64.zip.sha256"
  "${DIST}/Kimini-${VERSION}-windows-x86_64.zip"
  "${DIST}/Kimini-${VERSION}-windows-x86_64.zip.sha256"
  "${DIST}/Kimini-Web-${VERSION}-windows-x86_64.zip"
  "${DIST}/Kimini-Web-${VERSION}-windows-x86_64.zip.sha256"
)
UPDATE_FEEDS=(
  "${DIST}/Kimini-macos-aarch64.xml"
  "${DIST}/Kimini-Web-macos-aarch64.xml"
  "${DIST}/Kimini-macos-x86_64.xml"
  "${DIST}/Kimini-Web-macos-x86_64.xml"
)
PUBLISH_PACKAGES=("${PACKAGES[@]}")
if [[ "$INCLUDE_PORTABLE" -eq 1 ]]; then
  PUBLISH_PACKAGES+=("${PORTABLE_PACKAGES[@]}")
fi
ARTIFACTS=("${PUBLISH_PACKAGES[@]}" "${UPDATE_FEEDS[@]}")

echo "==> version ${VERSION}  tag ${TAG}"
echo "    title: ${TITLE}"
if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "    mode: dry-run (no tag / no publish)"
fi

if [[ -n "$(git status --porcelain 2>/dev/null || true)" ]]; then
  echo "warning: working tree is dirty — release will point at current HEAD" >&2
  git status --short >&2 || true
fi

# Prefer rustup-managed cargo so cross targets resolve.
if [[ -x "${CARGO_HOME:-$HOME/.cargo}/bin/cargo" ]]; then
  export PATH="${CARGO_HOME:-$HOME/.cargo}/bin:$PATH"
fi

if [[ "$SKIP_BUILD" -eq 0 ]]; then
  if command -v rustup >/dev/null 2>&1; then
    rustup target add aarch64-apple-darwin x86_64-apple-darwin
  fi
  echo "==> package both apps for aarch64 + x86_64 (DMG + zip)"
  for app in native web; do
    bash "$PACKAGE_SH" --app "$app" --target aarch64-apple-darwin --arch aarch64 --dmg --zip
    bash "$PACKAGE_SH" --app "$app" --target x86_64-apple-darwin --arch x86_64 --dmg --zip
  done
  if [[ "$INCLUDE_PORTABLE" -eq 1 ]]; then
    echo "==> package Linux x86_64 + aarch64 archives with Docker"
    bash "$ROOT/scripts/package-linux-docker.sh" --arch all
    echo "==> expecting Windows archives staged by scripts/package-windows.ps1"
  fi
else
  echo "==> skip build; expecting existing artifacts in ${DIST}"
fi

missing=0
for f in "${PUBLISH_PACKAGES[@]}"; do
  if [[ ! -f "$f" ]]; then
    echo "error: missing artifact: $f" >&2
    missing=1
  fi
done
if [[ "$missing" -ne 0 ]]; then
  echo "hint: run without --skip-build, or fix DIST/VERSION" >&2
  exit 1
fi
if [[ "$INCLUDE_PORTABLE" -eq 1 ]]; then
  echo "==> validate portable artifact checksums"
  for checksum in "${PORTABLE_PACKAGES[@]}"; do
    [[ "$checksum" == *.sha256 ]] || continue
    (
      cd "$(dirname "$checksum")"
      shasum -a 256 -c "$(basename "$checksum")"
    )
  done
fi

bash "$ROOT/scripts/fetch-sparkle.sh"
if [[ ! -x "$SIGN_SPARKLE_UPDATE" ]]; then
  echo "error: Sparkle signing helper missing: $SIGN_SPARKLE_UPDATE" >&2
  exit 1
fi

PUB_DATE="$(LC_ALL=C date -u '+%a, %d %b %Y %H:%M:%S +0000')"

generate_update_feed() {
  local app_title="$1"
  local artifact_name="$2"
  local arch="$3"
  local archive="${DIST}/${artifact_name}-${VERSION}-macos-${arch}.zip"
  local feed="${DIST}/${artifact_name}-macos-${arch}.xml"
  local signature
  signature="$("$SIGN_SPARKLE_UPDATE" "$archive")"

  printf '%s\n' \
    '<?xml version="1.0" encoding="utf-8"?>' \
    '<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">' \
    '  <channel>' \
    "    <title>${app_title} updates</title>" \
    '    <link>https://github.com/reedchan7/kimini/releases</link>' \
    '    <description>Secure macOS updates for Kimini.</description>' \
    '    <language>en</language>' \
    '    <item>' \
    "      <title>${app_title} ${VERSION}</title>" \
    "      <link>https://github.com/reedchan7/kimini/releases/tag/${TAG}</link>" \
    "      <sparkle:version>${VERSION}</sparkle:version>" \
    "      <sparkle:shortVersionString>${VERSION}</sparkle:shortVersionString>" \
    '      <sparkle:minimumSystemVersion>14.0</sparkle:minimumSystemVersion>' \
    "      <pubDate>${PUB_DATE}</pubDate>" \
    "      <enclosure url=\"https://github.com/reedchan7/kimini/releases/download/${TAG}/$(basename "$archive")\" ${signature} type=\"application/octet-stream\"/>" \
    '    </item>' \
    '  </channel>' \
    '</rss>' > "$feed"
  xmllint --noout "$feed"
}

echo "==> sign update archives and generate appcasts"
generate_update_feed "Kimini" "Kimini" "aarch64"
generate_update_feed "Kimini Web" "Kimini-Web" "aarch64"
generate_update_feed "Kimini" "Kimini" "x86_64"
generate_update_feed "Kimini Web" "Kimini-Web" "x86_64"

echo "==> artifacts"
ls -lh "${ARTIFACTS[@]}"
for f in "${ARTIFACTS[@]}"; do
  # zip is a container; dmg/app binary checks are best-effort via file(1)
  file -b "$f" | sed "s|^|    $(basename "$f"): |"
done

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo
  echo "Dry-run complete. Would publish:"
  echo "  tag:    $TAG"
  echo "  title:  $TITLE"
  printf '  assets:\n'
  for f in "${ARTIFACTS[@]}"; do
    echo "    - $f"
  done
  exit 0
fi

# Optional local git tag so the release points at a named ref in the clone.
if [[ "$NO_GIT_TAG" -eq 0 ]]; then
  if git rev-parse "$TAG" >/dev/null 2>&1; then
    existing="$(git rev-list -n 1 "$TAG")"
    head="$(git rev-parse HEAD)"
    if [[ "$existing" != "$head" ]]; then
      echo "error: tag $TAG already exists at $existing, but HEAD is $head" >&2
      echo "  bump Cargo.toml version, or delete the tag if it was a mistake" >&2
      exit 1
    fi
    echo "==> git tag $TAG already points at HEAD"
  else
    echo "==> git tag $TAG"
    git tag -a "$TAG" -m "Kimini ${TAG}"
  fi

  # Push tag if remote is missing it (best-effort detect origin).
  remote="$(git remote 2>/dev/null | awk 'NR==1{print; exit}')"
  remote="${remote:-origin}"
  if git ls-remote --tags "$remote" "refs/tags/${TAG}" 2>/dev/null | rg -q .; then
    echo "==> remote ${remote} already has ${TAG}"
  else
    echo "==> git push ${remote} ${TAG}"
    git push "$remote" "$TAG"
  fi
fi

# Publish or re-upload assets on an existing release.
release_args=(
  release create "$TAG"
  --title "$TITLE"
  --verify-tag
)
if [[ "$DRAFT" -eq 1 ]]; then
  release_args+=(--draft)
fi
if [[ -n "$NOTES_FILE" ]]; then
  release_args+=(--notes-file "$NOTES_FILE")
else
  release_args+=(--generate-notes)
fi
# Pre-release when version has a hyphen (e.g. 0.2.0-rc.1)
if [[ "$VERSION" == *-* ]]; then
  release_args+=(--prerelease)
fi

if gh release view "$TAG" >/dev/null 2>&1; then
  echo "==> release $TAG exists; uploading assets (clobber)"
  gh release upload "$TAG" "${ARTIFACTS[@]}" --clobber
  if [[ "$DRAFT" -eq 0 ]]; then
    # Ensure non-draft if caller wants a published release
    gh release edit "$TAG" --draft=false >/dev/null 2>&1 || true
  fi
else
  echo "==> gh ${release_args[*]} + assets"
  # --verify-tag fails if tag was not pushed (--no-git-tag); drop it then.
  if [[ "$NO_GIT_TAG" -eq 1 ]]; then
    filtered=()
    for a in "${release_args[@]}"; do
      [[ "$a" == "--verify-tag" ]] && continue
      filtered+=("$a")
    done
    release_args=("${filtered[@]}")
    release_args+=(--target "$(git rev-parse HEAD)")
  fi
  gh "${release_args[@]}" "${ARTIFACTS[@]}"
fi

echo
echo "Done. Release: $(gh release view "$TAG" --json url -q .url 2>/dev/null || echo "$TAG")"
echo "Assets:"
for f in "${ARTIFACTS[@]}"; do
  echo "  - $(basename "$f")"
done
